-- ********************************************************************
-- * Copyright Notice   : (c)2015,2016 Peng Liu.
-- * Filename           : base_var.sql
-- * Author             : Peng Liu
-- * Original           : 20160419
-- * Last Update        : 20160419
-- * Description        : query the archive log gap
-- *                      on standby database
-- *                      
-- * Usage              : be called by check.sql
-- ********************************************************************
SELECT * FROM V$ARCHIVE_GAP;
